package com.tony.Estados;

public enum Tipos_Area {
    este,
    lol,
    pediatria
//	Comunicaciones_e_Imagen_institucional,
//	Recursos_Humanos,
//	Presupuesto,
//	Programacion_de_Inversiones,
//	Informatica_y_Sistemas,
//	Contabilidad,
//	Tesoreria,
//	Logistica,
//	Desarrollo_Institucional,
//	Recaudacion_Tributaria,
//	pediatria,
//	Desarrollo_Productivo,
//	Desarrollo_Empresarial,
//	Seguridad_Ciudadana_y_Serenazgo,
//	Policia_Municipal,_Fiscalizacion_y_Control,
//	Transport,_Transito_y_Seguridad_Vial,
//	Registro_Civil,
//	DEMUNA,_OMAPED_y_CIAM,
//	Programas_Sociales,
//	Calidad_Ambiental_y_Proyectos,
//	Defensa_Civil,
//	Catastro_y_Desarrollo_Urbano,
//	Limpieza_Publica,_Parques,_Jardines_y_Ornato,
//	AAHH_y_Desarrollo_Rural,
//	Maquinaria_y_Equipo_Pesado,
//	Control_Patrimonial_y_Margesi_de_Bienes,
//	Secretaria_General,
//	Tramite_Documentario_y_Archivo_Central,
//	Alcalde,
//	Ejecutor_Coactivo
}
