package com.tony.Vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.tony.DaoImpl.DocumentImpl;
import com.tony.Estados.Estado_documento;
import com.tony.ServiceImpl.UsuarioInternoServiceImpl;
import com.tony.models.Documento.Documento;
import com.tony.models.UsuarioInterno.Usuario_interno;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableRowSorter;

class Edicion_documentos_Jinternal_frame_Mesa_Partes extends javax.swing.JInternalFrame {

    private TableRowSorter trsFiltro;
    private static Edicion_documentos_Jinternal_frame_Mesa_Partes edicion_documentos = null;
    private final Usuario_interno usuario_interno = Principal_Mesa_partes.usuario_interno;
    private final UsuarioInternoServiceImpl usuario_interno_service = Principal_Mesa_partes.userInternoService;
    private final DocumentImpl documento_impl = new DocumentImpl();
    private List<Documento> documentos = new ArrayList<>();
    private Documento documento_de_edicion;
    private int id_documento;
    private TextAutoCompleter llenar_area = null;
    private String texto_area = "";
    private TextAutoCompleter llenar_trabajadores = null;
    private List<Usuario_interno> lista_usuarios_interno_enviar;
    private Usuario_interno user_seleccionado = null;

    public static Edicion_documentos_Jinternal_frame_Mesa_Partes get_instancia_Edicion_Documentos() {
        if (edicion_documentos == null) {
            edicion_documentos = new Edicion_documentos_Jinternal_frame_Mesa_Partes();
        }
        return edicion_documentos;
    }

    private Edicion_documentos_Jinternal_frame_Mesa_Partes() {
        initComponents();
        this.jTableEdicion_docuementos.setModel(this.usuario_interno_service.get_all_documento_find_by_usuario_and_state_document(Estado_documento.Enviado, usuario_interno.getArea().getTipoArea(), jTableEdicion_docuementos));
        this.llenar_area = new TextAutoCompleter(this.jTextFieldArea_asignada);
        this.llenar_trabajadores = new TextAutoCompleter(this.jTextFieldPersona_Asignada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEdicion_documentos = new javax.swing.JDialog();
        jCPanel2 = new com.bolivia.panel.JCPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelAsunto_documento = new javax.swing.JLabel();
        jLabelID_Documento = new javax.swing.JLabel();
        jCheckBoxConformidad = new javax.swing.JCheckBox();
        jButtonEdicion_documentos = new javax.swing.JButton();
        jSpinnerforlio_presentado = new javax.swing.JSpinner();
        jLabelFolio_requrido = new javax.swing.JLabel();
        buttonGroupbutotn = new javax.swing.ButtonGroup();
        jDialogEnviar_Area = new javax.swing.JDialog();
        jCPanel4 = new com.bolivia.panel.JCPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldArea_asignada = new javax.swing.JTextField();
        jTextFieldPersona_Asignada = new javax.swing.JTextField();
        jButtonEnviar_Area = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabelNombre_Persona_Asginada = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelCargo_Persona_Asignada = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelDni_Persona_Asignada = new javax.swing.JLabel();
        jCPanel1 = new com.bolivia.panel.JCPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEdicion_docuementos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel_flujograma_documentos = new javax.swing.JPanel();
        jButtonEditar_Documento = new javax.swing.JButton();
        jRadioButtonUsuario = new javax.swing.JRadioButton();
        jRadioButtonAsunto_documento = new javax.swing.JRadioButton();
        jTextFieldBusqueda_documento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jDialogEdicion_documentos.setLocation(new java.awt.Point(250, 40));
        jDialogEdicion_documentos.setMinimumSize(new java.awt.Dimension(380, 520));
        jDialogEdicion_documentos.setModal(true);
        jDialogEdicion_documentos.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogEdicion_documentos.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        jDialogEdicion_documentos.setResizable(false);
        jDialogEdicion_documentos.setType(java.awt.Window.Type.UTILITY);
        jDialogEdicion_documentos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogEdicion_documentosWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogEdicion_documentosWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogEdicion_documentosWindowOpened(evt);
            }
        });

        jCPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jCPanel2.setUseMode(com.bolivia.panel.USEMODE.BICOLOR);
        jCPanel2.setVisibleLogo(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Edicion de Documentos.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("ID Documento:");

        jLabel5.setText("Asunto Documento");

        jLabel6.setText("Numero de folio presentados:");

        jLabel7.setText("Folio Necesario:");

        jLabel8.setText("Nombre del usuario:");

        jCheckBoxConformidad.setText("Disconforme");
        jCheckBoxConformidad.setEnabled(false);

        jButtonEdicion_documentos.setText("Editar Documento");
        jButtonEdicion_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdicion_documentosActionPerformed(evt);
            }
        });

        jSpinnerforlio_presentado.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerforlio_presentado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerforlio_presentadoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelID_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAsunto_documento, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxConformidad))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFolio_requrido, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerforlio_presentado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEdicion_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabelID_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAsunto_documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerforlio_presentado, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabelFolio_requrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxConformidad)
                .addGap(44, 44, 44)
                .addComponent(jButtonEdicion_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jCPanel2Layout = new javax.swing.GroupLayout(jCPanel2);
        jCPanel2.setLayout(jCPanel2Layout);
        jCPanel2Layout.setHorizontalGroup(
            jCPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jCPanel2Layout.setVerticalGroup(
            jCPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEdicion_documentosLayout = new javax.swing.GroupLayout(jDialogEdicion_documentos.getContentPane());
        jDialogEdicion_documentos.getContentPane().setLayout(jDialogEdicion_documentosLayout);
        jDialogEdicion_documentosLayout.setHorizontalGroup(
            jDialogEdicion_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogEdicion_documentosLayout.setVerticalGroup(
            jDialogEdicion_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEdicion_documentosLayout.createSequentialGroup()
                .addComponent(jCPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogEnviar_Area.setMinimumSize(new java.awt.Dimension(680, 400));
        jDialogEnviar_Area.setModal(true);
        jDialogEnviar_Area.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogEnviar_Area.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        jDialogEnviar_Area.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogEnviar_AreaWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogEnviar_AreaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogEnviar_AreaWindowOpened(evt);
            }
        });

        jCPanel4.setFirstColor(new java.awt.Color(204, 204, 255));
        jCPanel4.setSecondColor(new java.awt.Color(51, 51, 255));
        jCPanel4.setUseMode(com.bolivia.panel.USEMODE.BICOLOR);
        jCPanel4.setVisibleLogo(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Enviar a Area");

        jPanel2.setBackground(new java.awt.Color(204, 255, 102));

        jLabel10.setText("Asignar area:");

        jLabel11.setText("Asignar Persona Encargada");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextFieldArea_asignada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldArea_asignadaFocusLost(evt);
            }
        });

        jTextFieldPersona_Asignada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPersona_AsignadaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPersona_AsignadaFocusLost(evt);
            }
        });
        jTextFieldPersona_Asignada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPersona_AsignadaKeyPressed(evt);
            }
        });

        jButtonEnviar_Area.setText("Enviar area encargada");
        jButtonEnviar_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviar_AreaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Del Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel12.setText("Nombre:");

        jLabel13.setText("Cargo:");

        jLabel14.setText("Dni:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelDni_Persona_Asignada, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNombre_Persona_Asginada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCargo_Persona_Asignada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre_Persona_Asginada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCargo_Persona_Asignada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDni_Persona_Asignada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldArea_asignada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPersona_Asignada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonEnviar_Area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArea_asignada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPersona_Asignada))
                        .addGap(42, 42, 42)
                        .addComponent(jButtonEnviar_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jCPanel4Layout = new javax.swing.GroupLayout(jCPanel4);
        jCPanel4.setLayout(jCPanel4Layout);
        jCPanel4Layout.setHorizontalGroup(
            jCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanel4Layout.createSequentialGroup()
                .addGroup(jCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCPanel4Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jCPanel4Layout.setVerticalGroup(
            jCPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogEnviar_AreaLayout = new javax.swing.GroupLayout(jDialogEnviar_Area.getContentPane());
        jDialogEnviar_Area.getContentPane().setLayout(jDialogEnviar_AreaLayout);
        jDialogEnviar_AreaLayout.setHorizontalGroup(
            jDialogEnviar_AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEnviar_AreaLayout.createSequentialGroup()
                .addComponent(jCPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogEnviar_AreaLayout.setVerticalGroup(
            jDialogEnviar_AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEnviar_AreaLayout.createSequentialGroup()
                .addComponent(jCPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Edicion de Documentos"); // NOI18N

        jCPanel1.setFirstColor(new java.awt.Color(28, 194, 233));
        jCPanel1.setSecondColor(new java.awt.Color(0, 51, 153));
        jCPanel1.setUseMode(com.bolivia.panel.USEMODE.BICOLOR);
        jCPanel1.setVisibleLogo(false);

        jTableEdicion_docuementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_documento", "asunto", "usuario", "Dni del usuario", "Conforme?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEdicion_docuementos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEdicion_docuementosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEdicion_docuementos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Auditoria de Estado del documento.");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel_flujograma_documentos.setLayout(new java.awt.GridLayout(10, 1, 0, 80));
        jScrollPane2.setViewportView(jPanel_flujograma_documentos);

        jButtonEditar_Documento.setText("Editar Documento");
        jButtonEditar_Documento.setEnabled(false);
        jButtonEditar_Documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditar_DocumentoMouseClicked(evt);
            }
        });
        jButtonEditar_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditar_DocumentoActionPerformed(evt);
            }
        });

        buttonGroupbutotn.add(jRadioButtonUsuario);
        jRadioButtonUsuario.setText("Usuario");

        buttonGroupbutotn.add(jRadioButtonAsunto_documento);
        jRadioButtonAsunto_documento.setText("Asunto Documento");

        jTextFieldBusqueda_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBusqueda_documentoKeyTyped(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        javax.swing.GroupLayout jCPanel1Layout = new javax.swing.GroupLayout(jCPanel1);
        jCPanel1.setLayout(jCPanel1Layout);
        jCPanel1Layout.setHorizontalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCPanel1Layout.createSequentialGroup()
                .addGroup(jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jRadioButtonUsuario)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonAsunto_documento))
                    .addGroup(jCPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jTextFieldBusqueda_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jButtonEditar_Documento))
                    .addGroup(jCPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jCPanel1Layout.setVerticalGroup(
            jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCPanel1Layout.createSequentialGroup()
                        .addGroup(jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonUsuario)
                            .addComponent(jRadioButtonAsunto_documento)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar_Documento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBusqueda_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEdicion_docuementosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEdicion_docuementosMouseClicked
        if (this.jTableEdicion_docuementos.isColumnSelected(0) && this.jTableEdicion_docuementos.getRowSelectionAllowed()) {
            this.id_documento = Integer.parseInt(jTableEdicion_docuementos.getValueAt(jTableEdicion_docuementos.getSelectedRow(), 0).toString());
            this.usuario_interno_service.get_flujograma_documento(this.id_documento, jPanel_flujograma_documentos);
            this.jButtonEditar_Documento.setEnabled(true);
            if (this.llenar_area.getItems().length != 0) {
                this.llenar_area.removeAllItems();
            }
            if (this.jTableEdicion_docuementos.getValueAt(this.jTableEdicion_docuementos.getSelectedRow(), 4).toString().equalsIgnoreCase("conforme")) {
                this.jButtonEditar_Documento.setText("Enviar Area");
            } else {
                this.jButtonEditar_Documento.setText("Editar Documento");
            }

        } else {
            this.jButtonEditar_Documento.setEnabled(false);
            JOptionPane.showMessageDialog(this, "si desea ver el flujograma de tu documento del click al id ");
        }
    }//GEN-LAST:event_jTableEdicion_docuementosMouseClicked

    private void jTextFieldBusqueda_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBusqueda_documentoKeyTyped
        // TODO add your handling code here:
        jTextFieldBusqueda_documento.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextFieldBusqueda_documento.getText());
                jTextFieldBusqueda_documento.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(jTableEdicion_docuementos.getModel());
        jTableEdicion_docuementos.setRowSorter(trsFiltro);

    }//GEN-LAST:event_jTextFieldBusqueda_documentoKeyTyped

    private void jButtonEditar_DocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditar_DocumentoMouseClicked


    }//GEN-LAST:event_jButtonEditar_DocumentoMouseClicked

    private void jButtonEditar_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditar_DocumentoActionPerformed
        if (this.jButtonEditar_Documento.getText().equals("Editar Documento")) {
            if (!this.jDialogEdicion_documentos.isShowing()) {
                this.documento_de_edicion = this.usuario_interno_service.get_document_find_by_id_document(id_documento);
                this.jLabelNombreUsuario.setText(this.documento_de_edicion.getUsuario().getNombre());
                this.jLabelID_Documento.setText(String.valueOf(this.documento_de_edicion.getId_documento()));
                this.jLabelAsunto_documento.setText(this.documento_de_edicion.getAsunto());

                SpinnerNumberModel model = new SpinnerNumberModel(
                        new Integer(this.documento_de_edicion.getNum_foleo()), // Dato visualizado al inicio en el spinner 
                        new Integer(this.documento_de_edicion.getNum_foleo()), // Límite inferior 
                        new Integer(this.usuario_interno_service.get_tupa_find_by_asunto(this.documento_de_edicion.getAsunto()).getProceso()), // Límite superior 
                        new Integer(1) // incremento-decremento 
                );
                this.jSpinnerforlio_presentado.setModel(model);
                this.jLabelFolio_requrido.setText(String.valueOf(this.usuario_interno_service.get_tupa_find_by_asunto(this.documento_de_edicion.getAsunto()).getProceso()));
                this.jCheckBoxConformidad.setSelected(this.documento_de_edicion.getNum_foleo() < this.usuario_interno_service.get_tupa_find_by_asunto(this.documento_de_edicion.getAsunto()).getProceso());
                this.jDialogEdicion_documentos.setVisible(true);

            }
        } else if (this.jButtonEditar_Documento.getText().equals("Enviar Area")) {
            if (!this.jDialogEnviar_Area.isShowing()) {
                this.documento_de_edicion = this.usuario_interno_service.get_document_find_by_id_document(id_documento);
                System.out.println("Asinto del documento " + this.documento_de_edicion.getAsunto());

                this.usuario_interno_service.get_area_find_by_tupa(this.documento_de_edicion.getAsunto(), llenar_area);
                this.jDialogEnviar_Area.setVisible(true);
            }
        }

    }//GEN-LAST:event_jButtonEditar_DocumentoActionPerformed

    private void jButtonEdicion_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdicion_documentosActionPerformed

        if (this.documento_de_edicion.getNum_foleo() == Integer.parseInt(this.jSpinnerforlio_presentado.getValue().toString())) {
            JOptionPane.showMessageDialog(jDialogEdicion_documentos, " Modifica el numero de folios ");
        } else if (!this.documento_de_edicion.isDisconforme()) {
            JOptionPane.showMessageDialog(this.jDialogEdicion_documentos, "ya no se puede modificar el documento");
        } else {
            this.documento_de_edicion.setNum_foleo(Integer.parseInt(this.jSpinnerforlio_presentado.getValue().toString()));
            this.documento_de_edicion.setDisconforme(jCheckBoxConformidad.isSelected());
            if (this.usuario_interno_service.Editar_documento(documento_de_edicion)) {
                this.jButtonEdicion_documentos.setEnabled(false);
                JOptionPane.showMessageDialog(this.jDialogEdicion_documentos, " se edito correctamente");

            }
        }


    }//GEN-LAST:event_jButtonEdicion_documentosActionPerformed

    private void jSpinnerforlio_presentadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerforlio_presentadoStateChanged
        System.out.println("Se ejecuto el evento StateChanged");
        if (Integer.parseInt(jSpinnerforlio_presentado.getValue().toString()) < Integer.parseInt(this.jLabelFolio_requrido.getText())) {
            jCheckBoxConformidad.setSelected(true);
            return;
        } else if (Integer.parseInt(jSpinnerforlio_presentado.getValue().toString()) > Integer.parseInt(this.jLabelFolio_requrido.getText())) {
            JOptionPane.showMessageDialog(jDialogEdicion_documentos, "el numero de folios presentado debe ser igual o menor que los folios requerido");
            return;
        } else {
            jCheckBoxConformidad.setSelected(false);

        }

    }//GEN-LAST:event_jSpinnerforlio_presentadoStateChanged

    private void jDialogEnviar_AreaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEnviar_AreaWindowClosing
        if (this.llenar_area.getItems().length != 0) {
            this.llenar_area.removeAllItems();
        }
        this.jTextFieldArea_asignada.setText("");
        this.jTextFieldPersona_Asignada.setText("");
        this.jLabelNombre_Persona_Asginada.setText("");
        this.jLabelCargo_Persona_Asignada.setText("");
        this.jLabelDni_Persona_Asignada.setText("");
        this.jTableEdicion_docuementos.setModel(this.usuario_interno_service.get_all_documento_find_by_usuario_and_state_document(Estado_documento.Recepcionado, usuario_interno.getArea().getTipoArea(), jTableEdicion_docuementos));

    }//GEN-LAST:event_jDialogEnviar_AreaWindowClosing

    private void jDialogEnviar_AreaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEnviar_AreaWindowOpened

    }//GEN-LAST:event_jDialogEnviar_AreaWindowOpened

    private void jTextFieldPersona_AsignadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPersona_AsignadaFocusGained
        if (!this.texto_area.equals(this.jTextFieldArea_asignada.getText()) && this.jTextFieldArea_asignada.getText() != null) {
            //llenar el autocomplete de operadores
            this.lista_usuarios_interno_enviar = this.usuario_interno_service.get_usuario_interno_find_by_nombre_area(this.jTextFieldArea_asignada.getText(), llenar_trabajadores);
            this.lista_usuarios_interno_enviar.forEach(System.out::println);
            this.texto_area = this.jTextFieldArea_asignada.getText();
        } else if (this.jTextFieldArea_asignada.getText() == null) {
            JOptionPane.showMessageDialog(jDialogEnviar_Area, "primero Asigne una area");

        }
    }//GEN-LAST:event_jTextFieldPersona_AsignadaFocusGained

    private void jButtonEnviar_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviar_AreaActionPerformed
        if (this.jTextFieldArea_asignada.getText() != null && this.jTextFieldPersona_Asignada.getText() != null) {
            if (JOptionPane.showConfirmDialog(this.jDialogEnviar_Area, "Los datos son correctos?") == 0) {
                if (this.usuario_interno_service.Enviar_area_documento(documento_de_edicion, this.usuario_interno_service.get_usuario_interno_by_Dni(this.user_seleccionado.getDni())) && this.usuario_interno_service.add_operacion_estado_documento_usuario_interno(documento_de_edicion, Estado_documento.Enviado)) {
                    this.jButtonEnviar_Area.setEnabled(false);
                    JOptionPane.showMessageDialog(jDialogEnviar_Area, "Se Envio correctamente", "Envio", 1);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this.jDialogEnviar_Area, "faltan datos para enviar al area");
        }
    }//GEN-LAST:event_jButtonEnviar_AreaActionPerformed

    private void jTextFieldPersona_AsignadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPersona_AsignadaFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldPersona_AsignadaFocusLost

    private void jDialogEdicion_documentosWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEdicion_documentosWindowActivated
        // TODO add your handling code here:
        System.out.println("entro al evento Activated de JdialogEdicion_Documento");
        this.jButtonEdicion_documentos.setEnabled(true);
    }//GEN-LAST:event_jDialogEdicion_documentosWindowActivated

    private void jDialogEdicion_documentosWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEdicion_documentosWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_jDialogEdicion_documentosWindowOpened

    private void jDialogEnviar_AreaWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEnviar_AreaWindowActivated
        // TODO add your handling code here:
        this.jButtonEnviar_Area.setEnabled(true);
        System.out.println("entro al evento activate");
    }//GEN-LAST:event_jDialogEnviar_AreaWindowActivated

    private void jTextFieldArea_asignadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldArea_asignadaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldArea_asignadaFocusLost

    private void jTextFieldPersona_AsignadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPersona_AsignadaKeyPressed
        // TODO add your handling code here:
        if (((JTextField) evt.getComponent()).getText().length() >= 3 && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (this.jTextFieldPersona_Asignada.getText() != null && this.jTextFieldArea_asignada.getText() != null) {

                if (!this.lista_usuarios_interno_enviar.isEmpty()) {
                    this.user_seleccionado = (Usuario_interno) this.lista_usuarios_interno_enviar.stream()
                            .filter(user -> user.getNombre().equals(this.llenar_trabajadores.getItemSelected().toString()))
                            .findFirst().get();
                }
                System.out.println(" usuario seleccionado " + user_seleccionado.getNombre() + " " + user_seleccionado.getApellido());
                if (user_seleccionado != null) {
                    this.jLabelNombre_Persona_Asginada.setText(user_seleccionado.getNombre() + " " + user_seleccionado.getApellido());
                    this.jLabelCargo_Persona_Asignada.setText(user_seleccionado.getPerfil().getTipoPerfil().toString());
                    this.jLabelDni_Persona_Asignada.setText(String.valueOf(user_seleccionado.getDni()));
                }
            }
        }
    }//GEN-LAST:event_jTextFieldPersona_AsignadaKeyPressed

    private void jDialogEdicion_documentosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogEdicion_documentosWindowClosing
        this.jTableEdicion_docuementos.setModel(this.usuario_interno_service.get_all_documento_find_by_usuario_and_state_document(Estado_documento.Recepcionado, usuario_interno.getArea().getTipoArea(), jTableEdicion_docuementos));

    }//GEN-LAST:event_jDialogEdicion_documentosWindowClosing
    private void filtro() {
        int columna_Buscar = 0;
        if (this.jRadioButtonUsuario.isSelected()) {
            columna_Buscar = 2;
        } else if (this.jRadioButtonAsunto_documento.isSelected()) {
            columna_Buscar = 1;

        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(this.jTextFieldBusqueda_documento.getText(), columna_Buscar));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupbutotn;
    private javax.swing.JButton jButtonEdicion_documentos;
    private javax.swing.JButton jButtonEditar_Documento;
    private javax.swing.JButton jButtonEnviar_Area;
    private com.bolivia.panel.JCPanel jCPanel1;
    private com.bolivia.panel.JCPanel jCPanel2;
    private com.bolivia.panel.JCPanel jCPanel4;
    private javax.swing.JCheckBox jCheckBoxConformidad;
    private javax.swing.JDialog jDialogEdicion_documentos;
    private javax.swing.JDialog jDialogEnviar_Area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAsunto_documento;
    private javax.swing.JLabel jLabelCargo_Persona_Asignada;
    private javax.swing.JLabel jLabelDni_Persona_Asignada;
    private javax.swing.JLabel jLabelFolio_requrido;
    private javax.swing.JLabel jLabelID_Documento;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelNombre_Persona_Asginada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_flujograma_documentos;
    private javax.swing.JRadioButton jRadioButtonAsunto_documento;
    private javax.swing.JRadioButton jRadioButtonUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerforlio_presentado;
    private javax.swing.JTable jTableEdicion_docuementos;
    private javax.swing.JTextField jTextFieldArea_asignada;
    private javax.swing.JTextField jTextFieldBusqueda_documento;
    private javax.swing.JTextField jTextFieldPersona_Asignada;
    // End of variables declaration//GEN-END:variables
}
