/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tony.Vista;

import java.awt.Component;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author antony
 */
public class Edicion_documentos_Jinternal_frame_Mesa_Partes extends javax.swing.JInternalFrame {
    
    private static Edicion_documentos_Jinternal_frame_Mesa_Partes edicion_documentos = null;
    private ArrayList<JPanel> paneles = new ArrayList<>();
    
    public static Edicion_documentos_Jinternal_frame_Mesa_Partes get_instancia_Edicion_Documentos() {
        if (edicion_documentos == null) {
            edicion_documentos = new Edicion_documentos_Jinternal_frame_Mesa_Partes();
        }
        return edicion_documentos;
    }
    
    private Edicion_documentos_Jinternal_frame_Mesa_Partes() {
        initComponents();
      
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edicion_documentos_Jinternal_frame_Mesa_Partes().show();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelAll_documentos = new javax.swing.JPanel();
        jPanelDocumento_item = new javax.swing.JPanel();
        jPanelDocumento_detalle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDocumento_Detalle_item = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAsunto_Documento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEstado_Documento = new javax.swing.JLabel();
        jPanelUsuario_Detalle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Edicion de Documentos"); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelDocumento_item.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDocumento_item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDocumento_item.setLayout(new java.awt.GridLayout(2, 1));

        jPanelDocumento_detalle.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Documento/ic_import_contacts_white_24dp_2x.png"))); // NOI18N
        jLabel1.setText("1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelDocumento_Detalle_item.setBackground(new java.awt.Color(204, 255, 255));
        jPanelDocumento_Detalle_item.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Asunto:");
        jPanelDocumento_Detalle_item.add(jLabel2);

        jLabelAsunto_Documento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelDocumento_Detalle_item.add(jLabelAsunto_Documento);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estado Actual:");
        jPanelDocumento_Detalle_item.add(jLabel3);

        jLabelEstado_Documento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelDocumento_Detalle_item.add(jLabelEstado_Documento);

        javax.swing.GroupLayout jPanelDocumento_detalleLayout = new javax.swing.GroupLayout(jPanelDocumento_detalle);
        jPanelDocumento_detalle.setLayout(jPanelDocumento_detalleLayout);
        jPanelDocumento_detalleLayout.setHorizontalGroup(
            jPanelDocumento_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumento_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumento_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDocumento_Detalle_item, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDocumento_detalleLayout.setVerticalGroup(
            jPanelDocumento_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumento_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumento_Detalle_item, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDocumento_item.add(jPanelDocumento_detalle);

        jPanelUsuario_Detalle.setBackground(new java.awt.Color(255, 0, 0));

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Documento/ic_person_white_24dp_2x.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuario:");
        jPanel5.add(jLabel5);
        jPanel5.add(jLabelUsuario);

        javax.swing.GroupLayout jPanelUsuario_DetalleLayout = new javax.swing.GroupLayout(jPanelUsuario_Detalle);
        jPanelUsuario_Detalle.setLayout(jPanelUsuario_DetalleLayout);
        jPanelUsuario_DetalleLayout.setHorizontalGroup(
            jPanelUsuario_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addGroup(jPanelUsuario_DetalleLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelUsuario_DetalleLayout.setVerticalGroup(
            jPanelUsuario_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuario_DetalleLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanelDocumento_item.add(jPanelUsuario_Detalle);

        javax.swing.GroupLayout jPanelAll_documentosLayout = new javax.swing.GroupLayout(jPanelAll_documentos);
        jPanelAll_documentos.setLayout(jPanelAll_documentosLayout);
        jPanelAll_documentosLayout.setHorizontalGroup(
            jPanelAll_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAll_documentosLayout.createSequentialGroup()
                .addComponent(jPanelDocumento_item, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 877, Short.MAX_VALUE))
        );
        jPanelAll_documentosLayout.setVerticalGroup(
            jPanelAll_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAll_documentosLayout.createSequentialGroup()
                .addComponent(jPanelDocumento_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelAll_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jPanelAll_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(625, 625, 625))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAsunto_Documento;
    private javax.swing.JLabel jLabelEstado_Documento;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAll_documentos;
    private javax.swing.JPanel jPanelDocumento_Detalle_item;
    private javax.swing.JPanel jPanelDocumento_detalle;
    private javax.swing.JPanel jPanelDocumento_item;
    private javax.swing.JPanel jPanelUsuario_Detalle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
