/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tony.Vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.tony.Estados.Estado_documento;
import com.tony.ServiceImpl.AreaServiceImpl;
import com.tony.ServiceImpl.Tipo_documentoServiceImpl;
import com.tony.ServiceImpl.UsuarioInternoServiceImpl;
import com.tony.models.Documento.Documento;
import com.tony.models.Tupa;
import com.tony.models.UsuarioExterrno.UsuarioExterno;
import com.tony.models.UsuarioExterrno.UsuarioExternoJuridico;
import com.tony.models.UsuarioExterrno.UsuarioExternoNatural;
import com.tony.models.UsuarioInterno.Usuario_interno;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Registro_Usuario_documentos extends javax.swing.JInternalFrame {

    private int contador = 0;
    private static Registro_Usuario_documentos registro_usuario = null;
    private final UsuarioInternoServiceImpl usuario_interno_service = Principal_Mesa_partes.userInternoService;
    private final Usuario_interno usuario_interno = Principal_Mesa_partes.usuario_interno;
    private UsuarioExternoNatural UsuarioExternoNatural = null;
    private UsuarioExternoJuridico usuarioExternoJuridico = null;
    private final Tipo_documentoServiceImpl tipo_documento_service = new Tipo_documentoServiceImpl();
    private final AreaServiceImpl area_service;
    private TextAutoCompleter texto_autocompleter_tupac;
    private final TextAutoCompleter texto_autocompletado_area;
    private final TextAutoCompleter texto_autocompletado_tipo_document;
    private List<Tupa> lista_tupac = null;
    private UsuarioExterno usuarioExterno_temporal;
    private String texto_anterio = "";
    private Tipo_documentoServiceImpl tipo_documento = null;

    public static Registro_Usuario_documentos get_instancia_registro_usuario() {
        if (registro_usuario == null) {
            registro_usuario = new Registro_Usuario_documentos();
        }
        return registro_usuario;
    }

    private Registro_Usuario_documentos() {
        initComponents();
        lista_tupac = new ArrayList<>();
        this.area_service = new AreaServiceImpl();
        jPanelPersonaJuridica.setVisible(false);
        this.texto_autocompleter_tupac = new TextAutoCompleter(this.jTextFieldAsunto);
        this.texto_autocompletado_area = new TextAutoCompleter(this.jTextFieldArea);
        this.jPanelPersonaJuridica.setVisible(false);
        this.texto_autocompletado_tipo_document = new TextAutoCompleter(jTextFieldTipo_documento);
        this.jLabelUsuarioConocido.setVisible(false);
        this.tipo_documento = new Tipo_documentoServiceImpl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDocumentos = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelDocumento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombreCodigo_Documento = new javax.swing.JLabel();
        jLabelCodigo_Documento = new javax.swing.JLabel();
        jCheckBoxIsTupac = new javax.swing.JCheckBox();
        jTextFieldAsunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumeroFolioRequerido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumeroFolioPresentado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPlazo_resolucion_documento = new javax.swing.JTextField();
        jCheckBox_Conformidad = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton_SelecionarArchivo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Descripcion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldTipo_documento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabelNombre_archivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelDatos_usuarios = new javax.swing.JPanel();
        jLabel_Telefono = new javax.swing.JLabel();
        jTextField_Telefono = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel_DNI = new javax.swing.JLabel();
        jTextField_Apellido = new javax.swing.JTextField();
        jTextField_Correo = new javax.swing.JTextField();
        jLabel_Correo = new javax.swing.JLabel();
        jLabel_Apellido = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabelUsuarioConocido = new javax.swing.JLabel();
        jComboBoxTipoPersona = new javax.swing.JComboBox<>();
        jLabel_Tipo = new javax.swing.JLabel();
        jPanelPersonaJuridica = new javax.swing.JPanel();
        jLabel_Ruc = new javax.swing.JLabel();
        jTextField_Ruc = new javax.swing.JTextField();
        jLabel_Organizacion = new javax.swing.JLabel();
        jTextField_Organizacion = new javax.swing.JTextField();
        jButton_Aceptar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldDni_seach_registro = new javax.swing.JTextField();

        jDialogDocumentos.setFocusTraversalPolicyProvider(true);
        jDialogDocumentos.setMinimumSize(new java.awt.Dimension(659, 644));
        jDialogDocumentos.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogDocumentos.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        jDialogDocumentos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogDocumentosWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogDocumentosWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialogDocumentosWindowOpened(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelDocumento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DE DOCUMENTO");

        jLabelNombreCodigo_Documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombreCodigo_Documento.setText("CodigoDocumento");

        jLabelCodigo_Documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigo_Documento.setText("Codigo");

        jCheckBoxIsTupac.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxIsTupac.setText("Tupa");
        jCheckBoxIsTupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIsTupacActionPerformed(evt);
            }
        });
        jCheckBoxIsTupac.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheckBoxIsTupacPropertyChange(evt);
            }
        });

        jTextFieldAsunto.setNextFocusableComponent(jTextFieldTipo_documento);
        jTextFieldAsunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAsuntoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAsuntoFocusLost(evt);
            }
        });
        jTextFieldAsunto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldAsuntoInputMethodTextChanged(evt);
            }
        });
        jTextFieldAsunto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldAsuntoPropertyChange(evt);
            }
        });
        jTextFieldAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAsuntoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAsuntoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Asunto");

        jTextFieldArea.setNextFocusableComponent(jTextFieldAsunto);
        jTextFieldArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAreaFocusLost(evt);
            }
        });
        jTextFieldArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAreaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Area");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("#Foleo Requerido");

        jTextFieldNumeroFolioRequerido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNumeroFolioRequerido.setToolTipText("procedimiento");
        jTextFieldNumeroFolioRequerido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroFolioRequeridoActionPerformed(evt);
            }
        });
        jTextFieldNumeroFolioRequerido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroFolioRequeridoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Presentado");

        jTextFieldNumeroFolioPresentado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNumeroFolioPresentado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFolioPresentadoFocusLost(evt);
            }
        });
        jTextFieldNumeroFolioPresentado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroFolioPresentadoActionPerformed(evt);
            }
        });
        jTextFieldNumeroFolioPresentado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroFolioPresentadoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Plazo");

        jTextFieldPlazo_resolucion_documento.setToolTipText("plazo");

        jCheckBox_Conformidad.setText("Desconforme");
        jCheckBox_Conformidad.setEnabled(false);
        jCheckBox_Conformidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ConformidadActionPerformed(evt);
            }
        });

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(5);
        jScrollPane3.setViewportView(jTextAreaObservaciones);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Observaciones");

        jButton_SelecionarArchivo.setText("Seleccionar Archivo");
        jButton_SelecionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelecionarArchivoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Copia");

        jTextArea_Descripcion.setColumns(20);
        jTextArea_Descripcion.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Descripcion);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Descripcion");

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegistrar.setText("REGISTRAR");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Resetear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldTipo_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipo_documentoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tipo Documento");

        javax.swing.GroupLayout jPanelDocumentoLayout = new javax.swing.GroupLayout(jPanelDocumento);
        jPanelDocumento.setLayout(jPanelDocumentoLayout);
        jPanelDocumentoLayout.setHorizontalGroup(
            jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentoLayout.createSequentialGroup()
                                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldTipo_documento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentoLayout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxIsTupac, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123))))
                    .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabelNombreCodigo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelCodigo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(234, 234, 234)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_SelecionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNombre_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Conformidad)
                                .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                                    .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNumeroFolioRequerido, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNumeroFolioPresentado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(57, 57, 57)
                                    .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPlazo_resolucion_documento, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))))
                        .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelDocumentoLayout.setVerticalGroup(
            jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreCodigo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jCheckBoxIsTupac, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTipo_documento, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroFolioRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumeroFolioPresentado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlazo_resolucion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_Conformidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_SelecionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanelDocumento);

        javax.swing.GroupLayout jDialogDocumentosLayout = new javax.swing.GroupLayout(jDialogDocumentos.getContentPane());
        jDialogDocumentos.getContentPane().setLayout(jDialogDocumentosLayout);
        jDialogDocumentosLayout.setHorizontalGroup(
            jDialogDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogDocumentosLayout.setVerticalGroup(
            jDialogDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        setName("Agregar Usuario"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 235, 235));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Documento/ic_queue_black_48dp_2x.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        jPanel3.setBackground(new java.awt.Color(68, 68, 110));

        jPanelDatos_usuarios.setBackground(new java.awt.Color(68, 68, 110));

        jLabel_Telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(0, 153, 0));
        jLabel_Telefono.setText("Telefono");

        jTextField_Telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Telefono.setName("noRequerido"); // NOI18N

        jTextFieldDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDniFocusLost(evt);
            }
        });
        jTextFieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDniKeyPressed(evt);
            }
        });

        jLabel_DNI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DNI.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_DNI.setText("DNI");

        jTextField_Apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ApellidoActionPerformed(evt);
            }
        });

        jTextField_Correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Correo.setName("noRequerido"); // NOI18N

        jLabel_Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Correo.setForeground(new java.awt.Color(0, 153, 0));
        jLabel_Correo.setText("Correo");

        jLabel_Apellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Apellido.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Apellido.setText("Apellido");

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Nombre.setText("Nombre");

        jTextField_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreActionPerformed(evt);
            }
        });

        jLabelUsuarioConocido.setText("click para ver detalle");
        jLabelUsuarioConocido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarioConocidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatos_usuariosLayout = new javax.swing.GroupLayout(jPanelDatos_usuarios);
        jPanelDatos_usuarios.setLayout(jPanelDatos_usuariosLayout);
        jPanelDatos_usuariosLayout.setHorizontalGroup(
            jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                        .addComponent(jLabel_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                        .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                                .addComponent(jLabel_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jLabel_DNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUsuarioConocido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
        );
        jPanelDatos_usuariosLayout.setVerticalGroup(
            jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatos_usuariosLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelUsuarioConocido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jComboBoxTipoPersona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Juridico" }));
        jComboBoxTipoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPersonaActionPerformed(evt);
            }
        });

        jLabel_Tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Tipo.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Tipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Tipo.setText("Tipo Usuario:");

        jPanelPersonaJuridica.setBackground(new java.awt.Color(68, 68, 110));
        jPanelPersonaJuridica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Obligados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanelPersonaJuridica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Ruc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Ruc.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Ruc.setText("RUC:");
        jPanelPersonaJuridica.add(jLabel_Ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 40));

        jTextField_Ruc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelPersonaJuridica.add(jTextField_Ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 40));

        jLabel_Organizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Organizacion.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_Organizacion.setText("Organizacion:");
        jPanelPersonaJuridica.add(jLabel_Organizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jTextField_Organizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelPersonaJuridica.add(jTextField_Organizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 193, 40));

        jButton_Aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Aceptar.setText("ACEPTAR");
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Cancelar.setText("CANCELAR");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Buscar usuario registrado:");

        jTextFieldDni_seach_registro.setName("noRequerido"); // NOI18N
        jTextFieldDni_seach_registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDni_seach_registroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDni_seach_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelDatos_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDni_seach_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatos_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 440, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniKeyPressed
        JTextField field = (JTextField) evt.getComponent();
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo numero");
        } else if (field.getText().length() <= 8) {
            jTextFieldDni.setSelectedTextColor(Color.GREEN);
        } else {
            jTextFieldDni.setSelectedTextColor(Color.red);
            JOptionPane.showMessageDialog(this, "un dni solo debe tener 8 digitos");
        }
    }//GEN-LAST:event_jTextFieldDniKeyPressed

    private void jTextField_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ApellidoActionPerformed

    private void jTextField_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreActionPerformed

    private void jTextFieldDni_seach_registroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDni_seach_registroKeyPressed

        char validar = evt.getKeyChar();
        if (!Character.isLetter(validar)) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (jTextFieldDni_seach_registro.getText().length() == 8) {
//                    UsuarioExterno usuario_externo = this.userInternoService.get_usuario_externo_find_by_dni(Integer.parseInt(this.jTextFieldDni_seach_registro.getText()));
//
//                    this.userInternoService.Llenar_panel_field_class(jPanelDatos_usuarios, usuario_externo);

                } else {
                    JOptionPane.showMessageDialog(this, "ingrese los 8 numeros");
                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numero");
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldDni_seach_registroKeyPressed

    private void jComboBoxTipoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPersonaActionPerformed
        // TODO add your handling code here:
        if (jComboBoxTipoPersona.getSelectedItem().toString().equals("Juridico")) {
            jPanelPersonaJuridica.setVisible(true);
        } else {
            jPanelPersonaJuridica.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxTipoPersonaActionPerformed

    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed

        if (this.usuarioExterno_temporal == null) {
            if (this.usuario_interno_service.VerificacionJpanes(this.jPanelDatos_usuarios)) {
                JOptionPane.showMessageDialog(this, "Faltan datos");
                return;
            } else if (jComboBoxTipoPersona.getSelectedItem().toString().equals("Juridico")) {
                if (this.usuario_interno_service.VerificacionJpanes(jPanelPersonaJuridica)) {
                    JOptionPane.showMessageDialog(this, "faltan datos en la persona juridica");
                    return;
                }
            }
            if (JOptionPane.showConfirmDialog(this, "Son los datos Correctos?") == 0) {
                this.UsuarioExternoNatural = new UsuarioExternoNatural(jTextField_Nombre.getText(), jTextField_Apellido.getText(), Integer.parseInt(jTextFieldDni.getText()), jTextField_Correo.getText(), jTextField_Telefono.getText());
                UsuarioExternoNatural.setCorreo_electronico(jTextField_Correo.getText());
                if (this.jComboBoxTipoPersona.getSelectedItem().toString().equals("Juridico")) {
                    this.usuarioExternoJuridico = new UsuarioExternoJuridico(this.UsuarioExternoNatural.getNombre(), this.UsuarioExternoNatural.getApellido(), this.UsuarioExternoNatural.getDni(), this.UsuarioExternoNatural.getCorreo_electronico(), this.UsuarioExternoNatural.getTelefono(), Integer.parseInt(jTextField_Ruc.getText()), this.jTextField_Organizacion.getText());
                }
                //            this.userInternoService.CrearIdDocumento(jLabelCodigo_Documento);
                jDialogDocumentos.setVisible(true);

            }
        } else {
            jDialogDocumentos.setVisible(true);
        }


    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void jCheckBoxIsTupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIsTupacActionPerformed
        if (jCheckBoxIsTupac.isSelected()) {
            Calendar fecha = new GregorianCalendar();
            jLabelCodigo_Documento.setText(String.valueOf(fecha.get(Calendar.YEAR)) + String.valueOf(fecha.get(Calendar.MONTH)) + String.valueOf(fecha.get(Calendar.DAY_OF_MONTH)));
            this.area_service.LLenar_autcompleter(texto_autocompletado_area);
            //this.jTextFieldNumeroFolioRequerido.setEditable(false);
        } else {
            // this.jTextFieldNumeroFolioRequerido.setEditable(true);
            texto_autocompletado_area.removeAllItems();
            //this.limpiarDatos();
        }
    }//GEN-LAST:event_jCheckBoxIsTupacActionPerformed

    private void jCheckBoxIsTupacPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheckBoxIsTupacPropertyChange
        // TODO add your handling code here:
        System.out.println("entro ne property change");
    }//GEN-LAST:event_jCheckBoxIsTupacPropertyChange

    private void jTextFieldAsuntoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoFocusGained
        if (!jTextFieldArea.getText().isEmpty() && !this.texto_anterio.equals(jTextFieldArea.getText())) {
            System.out.println("entro al metodo");
            if (jTextFieldArea.getText().length() >= 3) {
                System.out.println("entro al if de .length()>=3");
                this.lista_tupac = this.area_service.get_tupa_find_by_area_name(this.jTextFieldArea.getText());
                this.area_service.llenar_autocompletar_tupa(this.jTextFieldArea.getText(), this.texto_autocompleter_tupac);
            } else {
                JOptionPane.showMessageDialog(jDialogDocumentos, "ingrese una area de al menos 4 caracteres");
            }
            this.texto_anterio = jTextFieldArea.getText();
        }
    }//GEN-LAST:event_jTextFieldAsuntoFocusGained

    private void jTextFieldAsuntoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoFocusLost

    }//GEN-LAST:event_jTextFieldAsuntoFocusLost

    private void jTextFieldAsuntoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("entro en el cambio de propiedad de jTextFieldAsunto");
    }//GEN-LAST:event_jTextFieldAsuntoInputMethodTextChanged

    private void jTextFieldAsuntoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAsuntoPropertyChange

    private void jTextFieldAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAreaFocusLost
//        if (jTextFieldArea.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(jDialogDocumentos, "Ingrese una area valida", "mensaje de confirmacio", 1);
//            this.texto_tupac.removeAllItems();
//            lista_tupac.stream().forEach((tupa_objet) -> {
//                lista_tupac.remove(tupa_objet);
//            });
//        }
    }//GEN-LAST:event_jTextFieldAreaFocusLost

    private void jTextFieldAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAreaActionPerformed

    private void jTextFieldNumeroFolioRequeridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFolioRequeridoActionPerformed
        /**/
    }//GEN-LAST:event_jTextFieldNumeroFolioRequeridoActionPerformed

    private void jTextFieldNumeroFolioRequeridoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFolioRequeridoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numero");
        }
    }//GEN-LAST:event_jTextFieldNumeroFolioRequeridoKeyTyped

    private void jTextFieldNumeroFolioPresentadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFolioPresentadoFocusLost
        if (!jTextFieldNumeroFolioRequerido.getText().equals("") && !jTextFieldNumeroFolioPresentado.getText().equals("")) {
            if (Integer.parseInt(jTextFieldNumeroFolioPresentado.getText()) < Integer.parseInt(this.jTextFieldNumeroFolioRequerido.getText())) {
                jCheckBox_Conformidad.setSelected(true);
                return;
            } else if (Integer.parseInt(jTextFieldNumeroFolioPresentado.getText()) > Integer.parseInt(this.jTextFieldNumeroFolioRequerido.getText())) {
                JOptionPane.showMessageDialog(jDialogDocumentos, "el numero de folios presentado debe ser igual o menor que los folios requerido");
                return;
            } else {
                jCheckBox_Conformidad.setSelected(false);

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroFolioPresentadoFocusLost

    private void jTextFieldNumeroFolioPresentadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFolioPresentadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroFolioPresentadoActionPerformed

    private void jTextFieldNumeroFolioPresentadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFolioPresentadoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numero");
        }
    }//GEN-LAST:event_jTextFieldNumeroFolioPresentadoKeyTyped

    private void jCheckBox_ConformidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ConformidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ConformidadActionPerformed

    private void jButton_SelecionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelecionarArchivoActionPerformed

        //        JFileChooser seleccionado = new JFileChooser();
        //        seleccionado.showOpenDialog(jDialogDocumentos);
        //        if (seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION) {
        //            archivo = seleccionado.getSelectedFile();
        //            if (archivo.canRead()) {
        //                if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {
        //
        //                    jTextField_NombreDelAchivo.setText(archivo.getName());
        //                    bytesImg = registro.AbrirAImagen(archivo);
        //                } else {
        //                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de imagen.");
        //                }
        //
        //            }
        //        }
    }//GEN-LAST:event_jButton_SelecionarArchivoActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        //        if (seleccionado.showDialog(null, "Guardar Archivo") == JFileChooser.APPROVE_OPTION) {
        //            archivo = seleccionado.getSelectedFile();
        //            if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {
        //                String respuesta = registro.GuardarImagen(archivo, bytesImg);
        //                if (respuesta != null) {
        //                    JOptionPane.showMessageDialog(null, respuesta);
        //                } else {
        //                    JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR EL ARCHIVO");
        //                }
        //            } else {
        //                JOptionPane.showMessageDialog(null, "FORMATO INCORRECTO");
        //
        //            }
        //        }
        //Desde Abajo estaba descomentad
        if (this.usuario_interno_service.VerificacionJpanes(jPanelDocumento)) {
            JOptionPane.showMessageDialog(jDialogDocumentos, "Faltan datos en el documento");
            return;
        } else if (JOptionPane.showConfirmDialog(jDialogDocumentos, "Los datos son correctos?") == 0) {

            Documento documento = new Documento(jTextFieldAsunto.getText(), this.tipo_documento.get_tipo_documento_find_by_name(jTextFieldTipo_documento.getText()), jTextArea_Descripcion.getText(), jTextAreaObservaciones.getText(), Integer.parseInt(jTextFieldNumeroFolioPresentado.getText()), jCheckBox_Conformidad.isSelected(), jCheckBoxIsTupac.isSelected());
            if (this.usuarioExterno_temporal == null) {
                if (this.usuarioExternoJuridico != null) {
                    this.usuarioExternoJuridico.addDocumento(documento);
                } else {
                    this.UsuarioExternoNatural.addDocumento(documento);
                }
            } else {
                this.usuarioExterno_temporal.addDocumento(documento);
            }

            //        Estaba antes descomentaod    DesktopNotify.showDesktopMessage("Un nuevo Documento fue agregado", "Asunto:" + documento.getAsunto() + " ", DesktopNotify.SUCCESS, 5000);
            //        Estaba antes descomentaod     this.userInternoService.CrearIdDocumento(jLabelCodigo_Documento);
            this.limpiar_datos_documento();

        }


    }//GEN-LAST:event_jButtonRegistrarActionPerformed
    private void limpiar_datos_documento() {
        this.jTextFieldArea.setText("");
        this.jTextFieldAsunto.setText("");
        this.jTextFieldTipo_documento.setText("");
        this.jTextFieldNumeroFolioRequerido.setText("");
        this.jTextFieldNumeroFolioPresentado.setText("");
        this.jTextFieldPlazo_resolucion_documento.setText("");
        this.jTextAreaObservaciones.setText("");
        this.jTextArea_Descripcion.setText("");
        this.jLabel9.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipo_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipo_documentoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameOpened

    private void jDialogDocumentosWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogDocumentosWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialogDocumentosWindowActivated

    private void jDialogDocumentosWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogDocumentosWindowOpened
        if (this.usuarioExterno_temporal != null) {
            this.tipo_documento_service.LLenar_autcompleter(this.texto_autocompletado_tipo_document, this.usuarioExterno_temporal.getDocumentos());

        } else {
            this.tipo_documento_service.LLenar_autcompleter(this.texto_autocompletado_tipo_document, new ArrayList<>());

        }
    }//GEN-LAST:event_jDialogDocumentosWindowOpened

    private void jDialogDocumentosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogDocumentosWindowClosing
        // TODO add your handling code here:
        if (this.usuarioExterno_temporal == null) {
            if (this.usuarioExternoJuridico != null) {
                this.usuarioExternoJuridico.setCodigo("antony");
                this.usuario_interno_service.Registrar_usuarioExterno(this.usuarioExternoJuridico, usuario_interno);
                this.usuarioExternoJuridico.getDocumentos().stream().forEach((documento) -> {
                    this.usuario_interno_service.Registrar_operacion_documento_usuario_interno(this.usuario_interno, documento, "Registro");
                    this.usuario_interno_service.add_operacion_estado_documento_usuario_interno(documento, Estado_documento.Recepcionado);
                });
            } else if (!this.UsuarioExternoNatural.getDocumentos().isEmpty()) {
                this.UsuarioExternoNatural.setCodigo("ap");
                this.usuario_interno_service.Registrar_usuarioExterno(this.UsuarioExternoNatural, this.usuario_interno);

                this.UsuarioExternoNatural.getDocumentos().stream().forEach((document) -> {
                    this.usuario_interno_service.Registrar_operacion_documento_usuario_interno(this.usuario_interno, document, "Registro");
                    this.usuario_interno_service.add_operacion_estado_documento_usuario_interno(document, Estado_documento.Recepcionado);
                });

            } else {
                JOptionPane.showMessageDialog(jDialogDocumentos, "ingrese al menos un documento");

            }

        } else {
            if (usuarioExterno_temporal.getDocumentos().isEmpty()) {
                JOptionPane.showConfirmDialog(jDialogDocumentos, "ingrese al menos un documentos");

            }
            this.usuario_interno_service.add_documentoUsuarioExterno(usuario_interno, usuarioExterno_temporal);
//            usuarioExterno_temporal.getDocumentos().stream().forEach((documentos) -> {
//                this.usuario_interno_service.Registrar_operacion_documento_usuario_interno(this.usuario_interno, documentos);
//                this.usuario_interno_service.add_operacion_estado_documento_usuario_interno(documentos, Estado_documento.Recepcionado);
//            });
        }

        this.usuarioExternoJuridico = null;
        this.UsuarioExternoNatural = null;
        this.usuarioExterno_temporal = null;
        this.usuario_interno_service.limpiarDatosPanel(jPanelPersonaJuridica);
        this.usuario_interno_service.limpiarDatosPanel(jPanelDatos_usuarios);
        this.usuario_interno_service.limpiarDatosPanel(jPanelDocumento);
        if (this.jLabelUsuarioConocido.isShowing()) {
            this.jLabelUsuarioConocido.setVisible(false);
        }
    }//GEN-LAST:event_jDialogDocumentosWindowClosing
    String Texto_anterior = "";
    private void jTextFieldDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDniFocusLost
        JTextField field = (JTextField) evt.getComponent();
        if (!field.getText().isEmpty() && !Texto_anterior.equals(field.getText())) {
            this.jLabelUsuarioConocido.setVisible(false);
            usuarioExterno_temporal = this.usuario_interno_service.get_usuario_externo_find_by_dni(Integer.parseInt(field.getText()));
            if (this.usuarioExterno_temporal != null) {
                this.jLabelUsuarioConocido.setVisible(true);
            } else {
                this.jLabelUsuarioConocido.setVisible(false);

            }
            Texto_anterior = this.jTextFieldDni.getText();
        }
    }//GEN-LAST:event_jTextFieldDniFocusLost

    private void jLabelUsuarioConocidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarioConocidoMouseClicked
        // TODO add your handling code here:
        if (this.usuarioExterno_temporal != null) {

            JOptionPane.showMessageDialog(this, "Nombre " + this.usuarioExterno_temporal.getNombre() + " Apellido " + this.usuarioExterno_temporal.getApellido() + " Dni " + this.usuarioExterno_temporal.getDni());
        }
    }//GEN-LAST:event_jLabelUsuarioConocidoMouseClicked

    private void jTextFieldAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAreaFocusGained
        // TODO add your handling code here:
        if (((JTextField) evt.getComponent()).getText().isEmpty()) {
            this.jTextFieldAsunto.setText("");
        }
    }//GEN-LAST:event_jTextFieldAreaFocusGained

    private void jTextFieldAsuntoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoKeyPressed


    }//GEN-LAST:event_jTextFieldAsuntoKeyPressed

    private void jTextFieldAsuntoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAsuntoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyCode.ENTER.impl_getCode()) {
            if (!this.jTextFieldAsunto.getText().isEmpty() && this.lista_tupac != null) {
                Tupa tupa = this.lista_tupac.stream().filter((tupac) -> tupac.getProcedimiento().equalsIgnoreCase(this.texto_autocompleter_tupac.getItemSelected().toString())).findFirst().get();

                if (tupa != null) {
                    this.jTextFieldNumeroFolioRequerido.setText(String.valueOf(tupa.getProceso()));
                    this.jTextFieldPlazo_resolucion_documento.setText(String.valueOf(tupa.getPlazo()));
                }
            } else {
                JOptionPane.showMessageDialog(jDialogDocumentos, "Ingrese el asunto antes de continuar");
            }
        }
    }//GEN-LAST:event_jTextFieldAsuntoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_SelecionarArchivo;
    private javax.swing.JCheckBox jCheckBoxIsTupac;
    private javax.swing.JCheckBox jCheckBox_Conformidad;
    private javax.swing.JComboBox<String> jComboBoxTipoPersona;
    private javax.swing.JDialog jDialogDocumentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodigo_Documento;
    private javax.swing.JLabel jLabelNombreCodigo_Documento;
    private javax.swing.JLabel jLabelNombre_archivo;
    private javax.swing.JLabel jLabelUsuarioConocido;
    private javax.swing.JLabel jLabel_Apellido;
    private javax.swing.JLabel jLabel_Correo;
    private javax.swing.JLabel jLabel_DNI;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Organizacion;
    private javax.swing.JLabel jLabel_Ruc;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_Tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatos_usuarios;
    private javax.swing.JPanel jPanelDocumento;
    private javax.swing.JPanel jPanelPersonaJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaObservaciones;
    private javax.swing.JTextArea jTextArea_Descripcion;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldAsunto;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldDni_seach_registro;
    private javax.swing.JTextField jTextFieldNumeroFolioPresentado;
    private javax.swing.JTextField jTextFieldNumeroFolioRequerido;
    private javax.swing.JTextField jTextFieldPlazo_resolucion_documento;
    private javax.swing.JTextField jTextFieldTipo_documento;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Correo;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Organizacion;
    private javax.swing.JTextField jTextField_Ruc;
    private javax.swing.JTextField jTextField_Telefono;
    // End of variables declaration//GEN-END:variables
}
